// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDvo7_wRErtPXhyIo1ETXDMcotpLUM3bBw',
    appId: '1:932444280515:web:ab02084029df3a93567476',
    messagingSenderId: '932444280515',
    projectId: 'check-in-check-out-71f2e',
    authDomain: 'check-in-check-out-71f2e.firebaseapp.com',
    storageBucket: 'check-in-check-out-71f2e.appspot.com',
    measurementId: 'G-0EGXYQSL2W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDVibOQ5cZCsTFPdsF_B_YeePQxyR0--FI',
    appId: '1:932444280515:android:e1a7483c9194b2db567476',
    messagingSenderId: '932444280515',
    projectId: 'check-in-check-out-71f2e',
    storageBucket: 'check-in-check-out-71f2e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAg3eD7qo4h2aP98XccHgrTYOTvKWI0Yx0',
    appId: '1:932444280515:ios:60dce963b98abf9a567476',
    messagingSenderId: '932444280515',
    projectId: 'check-in-check-out-71f2e',
    storageBucket: 'check-in-check-out-71f2e.appspot.com',
    iosBundleId: 'com.apexStodio.inOut',
  );
}
